### ISSUE TITLE
Problems with Response Header

### ISSUE THREAD

**Issue by kingferiol** [duartemendes/aws-sam-api-proxy#3]
Hi,

We are experimenting issue with response headers (goal is work with CORS)

This code in our lambda function but we are not able to see headers in the answer 

```
awsProxyResponse.getHeaders().put(
	"Access-Control-Allow-Origin", "*"
);
awsProxyResponse.getHeaders().put(
	"Access-Control-Allow-Credentials", "true"
);
awsProxyResponse.getHeaders().put(
	"Access-Control-Allow-Headers",
	"Access-Control-Allow-Origin, Content-Type"
);
awsProxyResponse.getHeaders().put(
	"Access-Control-Allow-Methods", "GET,POST,PUT,DELETE,OPTIONS,HEAD"
);
```

We tried also adding this in yaml file 

 ```
     Events:
        MyApp:
          Type: AWS::Serverless::Api
          Properties:
            Path: /myapp/{proxy+}
            Method: any
            Cors:
              AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,HEAD'"
              AllowHeaders: "'Access-Control-Allow-Headers, Access-Control-Allow-Origin, Content-Type'"
              AllowOrigin: "'*'"
              AllowCredentials: True
```

Thanks a lot for any help
